//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNWomen.Prototype.Web.Prototype {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/UNWomen.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNWomen.Prototype.Web.Prototype.Actor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNWomen.Prototype.Web.Prototype.Movie))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actor", Namespace="http://schemas.datacontract.org/2004/07/UNWomen.Prototype.Entities")]
    [System.SerializableAttribute()]
    public partial class Actor : UNWomen.Prototype.Web.Prototype.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImdbIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActorId {
            get {
                return this.ActorIdField;
            }
            set {
                if ((this.ActorIdField.Equals(value) != true)) {
                    this.ActorIdField = value;
                    this.RaisePropertyChanged("ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImdbId {
            get {
                return this.ImdbIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImdbIdField, value) != true)) {
                    this.ImdbIdField = value;
                    this.RaisePropertyChanged("ImdbId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/UNWomen.Prototype.Entities")]
    [System.SerializableAttribute()]
    public partial class Movie : UNWomen.Prototype.Web.Prototype.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImdbIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImdbId {
            get {
                return this.ImdbIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImdbIdField, value) != true)) {
                    this.ImdbIdField = value;
                    this.RaisePropertyChanged("ImdbId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseYear {
            get {
                return this.ReleaseYearField;
            }
            set {
                if ((this.ReleaseYearField.Equals(value) != true)) {
                    this.ReleaseYearField = value;
                    this.RaisePropertyChanged("ReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Prototype.IMovieManager")]
    public interface IMovieManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/AddMovie", ReplyAction="http://tempuri.org/IMovieManager/AddMovieResponse")]
        void AddMovie(UNWomen.Prototype.Web.Prototype.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/AddMovie", ReplyAction="http://tempuri.org/IMovieManager/AddMovieResponse")]
        System.Threading.Tasks.Task AddMovieAsync(UNWomen.Prototype.Web.Prototype.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/GetMovie", ReplyAction="http://tempuri.org/IMovieManager/GetMovieResponse")]
        UNWomen.Prototype.Web.Prototype.Movie GetMovie(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/GetMovie", ReplyAction="http://tempuri.org/IMovieManager/GetMovieResponse")]
        System.Threading.Tasks.Task<UNWomen.Prototype.Web.Prototype.Movie> GetMovieAsync(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/GetActorsForMovie", ReplyAction="http://tempuri.org/IMovieManager/GetActorsForMovieResponse")]
        UNWomen.Prototype.Web.Prototype.Actor[] GetActorsForMovie(UNWomen.Prototype.Web.Prototype.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieManager/GetActorsForMovie", ReplyAction="http://tempuri.org/IMovieManager/GetActorsForMovieResponse")]
        System.Threading.Tasks.Task<UNWomen.Prototype.Web.Prototype.Actor[]> GetActorsForMovieAsync(UNWomen.Prototype.Web.Prototype.Movie movie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieManagerChannel : UNWomen.Prototype.Web.Prototype.IMovieManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieManagerClient : System.ServiceModel.ClientBase<UNWomen.Prototype.Web.Prototype.IMovieManager>, UNWomen.Prototype.Web.Prototype.IMovieManager {
        
        public MovieManagerClient() {
        }
        
        public MovieManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddMovie(UNWomen.Prototype.Web.Prototype.Movie movie) {
            base.Channel.AddMovie(movie);
        }
        
        public System.Threading.Tasks.Task AddMovieAsync(UNWomen.Prototype.Web.Prototype.Movie movie) {
            return base.Channel.AddMovieAsync(movie);
        }
        
        public UNWomen.Prototype.Web.Prototype.Movie GetMovie(int movieId) {
            return base.Channel.GetMovie(movieId);
        }
        
        public System.Threading.Tasks.Task<UNWomen.Prototype.Web.Prototype.Movie> GetMovieAsync(int movieId) {
            return base.Channel.GetMovieAsync(movieId);
        }
        
        public UNWomen.Prototype.Web.Prototype.Actor[] GetActorsForMovie(UNWomen.Prototype.Web.Prototype.Movie movie) {
            return base.Channel.GetActorsForMovie(movie);
        }
        
        public System.Threading.Tasks.Task<UNWomen.Prototype.Web.Prototype.Actor[]> GetActorsForMovieAsync(UNWomen.Prototype.Web.Prototype.Movie movie) {
            return base.Channel.GetActorsForMovieAsync(movie);
        }
    }
}
